name: img2card
channels:
  - conda-forge
dependencies:
  - python=3.10
  - openai=1.3.9
  - tiktoken=0.5.2
  - rich=13.7.0
  - pydantic=2.5.2
  - pydantic-settings=2.1.0
  - pillow=10.1.0
  - pip
  - pip:
    - loguru==0.7.2
    - piexif==1.1.3
    - python-telegram-bot[webhooks]==20.7
    - google-search-results==2.4.2
