name: Build and Push Docker Images

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Change this to your default branch if not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push API Docker image
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        file: ./docker/api.Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/api:latest
          ghcr.io/${{ github.repository }}/api:${{ github.run_number }}

    - name: Build and push Bot Docker image
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        file: ./docker/bot.Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/bot:latest
          ghcr.io/${{ github.repository }}/bot:${{ github.run_number }}

    - name: Build and push Card App Docker image
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        file: ./docker/app.Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/app:latest
          ghcr.io/${{ github.repository }}/app:${{ github.run_number }}
